### ISSUE TITLE
has mint changed manual transactions?

### ISSUE THREAD

**Issue by jimmyknowles** [nathanielkam/mint-csv-import#1]
I set out to use your method for adding credit card transactions that Mint deleted due to a card getting shut down and things getting transferred to the replacement card. But when I went to use your script, it appears that Mint only allows adding manual transactions for cash, check, and pending. Has that changed since you imported yours? Or were you using one of those three options (cash, check, pending)?

EDIT: I looked at the youtube video and he added his as cash transactions. I guess you just don't care if it's a cash transaction and not tied to a CC, it's just important that the transactions are in there.

And just curious, any reason why you used curl over the python requests library?

**Comment by nathanielkam** [comment]
@jimmyknowles due to mint restriction it needs to go in as one of the described methods. For my personal reasons (creating average monthly run budgets) this was acceptable. You do have the option to tag the transactions as a 2ndary description though that is not ideal it is the current limitation of Mint's interface. 

As far as curl vs python requests it was more just because it's easier to demonstrate from the browser as you can copy and paste it directly from network tab. There is no technical reason not to use requests and performance could be increased with requests + threading. That said, the tradeoff was also fairly minimal I think I did something in the range of ~1700 transactions using the curl method.

**Comment by jimmyknowles** [comment]
@nathanielkam thanks a lot for your response. This was a RTFM moment, so I apologize. The mint limitations are stated clearly in several spots, but like usual I jumped in and didn't read.

My needs are the same as yours, so it will work just fine. I just want my lost transactions back so I can look at monthly budgets.

I was getting a 255 error with the curl, so switched everything over to use requests and it works fine. I have more experience w/ requests, so it was easier to troubleshoot. Thanks for helping me find a way to recover my lost transactions.

**Comment by nathanielkam** [comment]
@jimmyknowles haha no worries, happens to everyone. Glad to hear it is of use for you too.
